# Generated by Django 5.0.3 on 2024-03-19 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
    ]
