# Generated by Django 5.0.3 on 2024-03-19 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_auto_20240319_1530'),
    ]

    operations = [
    ]
