# Generated by Django 5.0.3 on 2024-03-19 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_auto_20240319_1546'),
    ]

    operations = [
    ]
